# fly.toml
app = "ramadan-competition"
primary_region = "fra"

[mounts]
source = "data"
destination = "/data"  # Volume path for SQLite

[http_service]
internal_port = 8000    # Must match your app’s port
force_https = true
auto_start_machines = true
auto_stop_machines = true