app = "ramadan-competition"
primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000

[[mounts]]
destination = "/data"
source = "data"